version: '3.8'
services:
 
  gatepass:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "Saboka@12"
      ACCEPT_EULA: "Y"
    ports:
      - "8001:1433"
    volumes:
      - sql-gatepass-data:/var/opt/mssql  # Specify the volume for SQL Server data
    restart: always
    
  gatepass-app:
  
    container_name: gatepassapp-container
    build:
      context: .
      dockerfile: Dockerfile
    image: gatepassapp
    ports:
      - "8080:8080" 
       
    depends_on:
      - gatepass
    volumes:
      - app-data:/app/data  # Specify the volume for the application data
    restart: always

volumes:
  sql-gatepass-data:
  app-data:
